version: 0.2

env:
  parameter-store:
    DOCKER_CREDS_USERNAME: /kaizen_app/docker_creds/username
    DOCKER_CREDS_PASSWORD: /kaizen_app/docker_creds/password
    DOCKER_URL: /kaizen_app/docker_url/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing Python dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building Docker image"
      - echo "$DOCKER_CREDS_PASSWORD" | docker login -u "$DOCKER_CREDS_USERNAME" --password-stdin "$DOCKER_URL"
      - docker build -t "$DOCKER_URL/$DOCKER_CREDS_USERNAME/kaizen_app:latest" .
      - echo "Pushing Docker image to Docker Hub Repository"
      - docker push "$DOCKER_URL/$DOCKER_CREDS_USERNAME/kaizen_app:latest"
      - docker images
  post_build:
    commands:
      - echo "Build completed successfully"
